export const typeColors = {
  normal: "--poke-normal",
  fire: "--poke-fire",
  water: "--poke-water",
  grass: "--poke-grass",
  electric: "--poke-electric",
  ice: "--poke-ice",
  fighting: "--poke-fighting",
  poison: "--poke-poison",
  ground: "--poke-ground",
  flying: "--poke-flying",
  psychic: "--poke-psychic",
  bug: "--poke-bug",
  rock: "--poke-rock",
  ghost: "--poke-ghost",
  dragon: "--poke-dragon",
  dark: "--poke-dark",
  steel: "--poke-steel",
  fairy: "--poke-fairy",
  stellar: "--poke-stellar",
  unknown: "--poke-unknown",
  todos: "--poke-dark-gray",
  favs: "--poke-red",
};

export const traduccionTipos = {
  normal: "Normal",
  fire: "Fuego",
  water: "Agua",
  grass: "Planta",
  electric: "Eléctrico",
  ice: "Hielo",
  fighting: "Lucha",
  poison: "Veneno",
  ground: "Tierra",
  flying: "Volador",
  psychic: "Psíquico",
  bug: "Bicho",
  rock: "Roca",
  ghost: "Fantasma",
  dragon: "Dragón",
  dark: "Siniestro",
  steel: "Acero",
  fairy: "Hada",
  stellar: "Estrella",
  unknown: "Desconocido",
};

export const traduccionStats = {
  hp: "Salud",
  attack: "Ataque",
  defense: "Defensa",
  "special-attack": "At-especial",
  "special-defense": "Def-especial",
  speed: "Velocidad",
};
